spring:
  application:
    name: AssessmentApplication

  datasource:
    username: root
    password: assessment
    url: com.mysql.jdbc
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.
    hibernate:
      ddl-auto: update
    database: MYSQL
    show-sql: false
    generate-ddl: true

server:
  port: 8080
  shutdown: GRACEFUL